<a href="https://colab.research.google.com/github/chayakonchanlun/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
#การรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ Matrix)

# Numpy Array

# สร้าง numpy **array**

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) 
# สร้าง numpy array ที่มี 2 เเถว 3 หลัก สร้าง matrix จาก list

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape 
# เช็คขนาด (เเถว,หลัก)

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## matrix **transpose**

In [6]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### **สร้าง matrix เริ่มต้น (zeros,ones)**

In [7]:
np_z = np.zeros((4,5))   # matrix เริ่มต้นคือ matrix ที่กำหนดค่าให้เป็น 0,1
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np_200 = 200 * np.ones((4,7))
np_200 # ทำเป็นค่า 200 ทุกค่าใน matrix เอา 200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random **ค่าเเบบมั่ว**

In [10]:
np.random.randn(5,5) 
#random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-1.32949584,  1.03081802,  1.12743771,  0.06714979, -1.00010395],
       [ 0.49697251,  0.07665281, -0.1313927 ,  0.85006071,  0.8993744 ],
       [-0.67331798, -0.91602742, -0.55970203,  0.68106199,  1.24199273],
       [-2.77716968,  0.8336707 ,  0.39872361,  0.24619318,  1.46334264],
       [-0.19200002, -0.01402564, -0.18095631, -1.09313012, -0.86850188]])

In [11]:
2+(5*np.random.randn(3,3)) 
#normal distribution ที่มี mu=2 std=5

array([[ 7.40020408,  8.76478586, -4.46828451],
       [ 3.10267462, -6.668142  , -4.19911658],
       [-1.00528859,  2.2136637 , 10.31669272]])

In [12]:
np.random.randint(5,11,(4,5)) 
#ค่าตั้งเเต่ระหว่าง 5 ถึง 10 (5,11,(ขนาด 4x5))

array([[ 9,  7,  7,  9,  9],
       [ 8,  9,  6,  6,  5],
       [ 9, 10,  9,  6,  8],
       [ 6, 10,  7,  6,  7]])

## matrix **properties**

In [13]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np_a.T  #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
1 + np_a  #adding scalar to matrix

array([[2, 3, 4],
       [5, 6, 7]])

In [16]:
2 * np_a  #multipling scalar to matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [18]:
np_a + np_c  #adding matrix to matrix

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
np_a.shape

(2, 3)

In [20]:
np_c.shape

(2, 3)

In [21]:
np_c.T.shape

(3, 2)

In [22]:
np.dot(np_a,np_c.T)  #multipling matrix to matrix   (a,b) x (b,c) = (a,c)

array([[28, 10],
       [73, 28]])

## Indexing & **Slicing**

In [23]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np_a[1,1]

5

In [25]:
np_a[:2,:2]


array([[1, 2],
       [4, 5]])

In [26]:
np_a[0,:]

array([1, 2, 3])

## Useful **functions**

In [27]:

np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.sum(np_a)

21

In [29]:
np.sum(np_a,axis=0)  # axis 0 ก็คือรวมเลขในแต่ละแถว

array([5, 7, 9])

In [30]:
np.sum(np_a,axis=1)  # axis 1 ก็คือรวมเลขในแต่ละหลัก

array([ 6, 15])

In [31]:
np.mean(np_a)

3.5

In [32]:
np.mean(np_a,axis=0)  #หา mean ของ column

array([2.5, 3.5, 4.5])

## **วนลูปเอง**
# **summation**

In [33]:
np_a.shape

(2, 3)

In [34]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]}  sum_all={sum_all}')
print(sum_all)

we are at row=0,col=0 np_a[0,0]=1  sum_all=1
we are at row=0,col=1 np_a[0,1]=2  sum_all=3
we are at row=0,col=2 np_a[0,2]=3  sum_all=6
we are at row=1,col=0 np_a[1,0]=4  sum_all=10
we are at row=1,col=1 np_a[1,1]=5  sum_all=15
we are at row=1,col=2 np_a[1,2]=6  sum_all=21
21


In [35]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


# **Quiz กลุ่ม**
## **วนลูปหาค่า**

np.sum(np_a,axis=1)

np.mean(np_a)

np.mean(np_a,axis=0)

np.mean(np_a,axis=1)

np.max(np_a)

np.max(np_a,axis=0)

np.max(np_a,axis=1)

np.min(np_a)

np.min(np_a,axis=0)

np.min(np_a,axis=1)

In [36]:
sum_all = np.zeros(np_a.shape[0])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[row] = sum_all[row] + np_a[row,col]     
print(sum_all)

[ 6. 15.]


In [37]:
mean_all = 0
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        mean_all = mean_all + np_a[row,col]
mean_all = mean_all/(np_a.shape[0]*np_a.shape[1])
print(mean_all)

3.5


In [38]:
mean_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        mean_all[col] = mean_all[col] + np_a[row,col]/np_a.shape[0]
print(mean_all)

[2.5 3.5 4.5]


In [39]:
sum_all = np.zeros(np_a.shape[0])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[row] = sum_all[row] + np_a[row,col]
sum_all = sum_all/np_a.shape[1]
print(sum_all)

[2. 5.]


In [40]:
max_a = -100000000
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if np_a[row,col] > max_a :
            max_a = np_a[row,col]
print(max_a)

6


In [41]:
max_all = -100000 * np.ones(np_a.shape[1])
for col in range(np_a.shape[1]):
    for row in range(np_a.shape[0]):
        if np_a[row,col] > max_all[col]: 
            max_all[col] = np_a[row,col]
print(max_all)

[4. 5. 6.]


In [42]:
max_all = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
    max_all[row] = max(np_a[row,:])
print(max_all)

[3. 6.]


In [43]:
minV = 100000
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if np_a[row,col] < minV:
            minV = np_a[row,col]
print(minV)

1


In [44]:
min_all = np.zeros(np_a.shape[1])

for col in range(np_a.shape[1]):
    min_all[col] = min(np_a[:,col])
print(min_all)

[1. 2. 3.]


In [45]:
min_row = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
   min_row[row] = min(np_a[row,:])
print(min_row)

[1. 4.]
